[package]
name = 'php/php'
version = '8.3.4-beta.1'
description = 'PHP is a popular general-purpose scripting language that is especially suited to web development. Fast, flexible and pragmatic, PHP powers everything from your blog to the most popular websites in the world. PHP is distributed under the PHP License v3.01.'

# See more keys and definitions at https://docs.wasmer.io/registry/manifest

[dependencies]

[[module]]
name = 'php'
source = 'php.wasm'
abi = 'wasi'

[[command]]
name = 'php'
module = 'php'