[package]
name = 'php/php-eh'
version = '8.3.404-beta.4'
description = 'PHP with wasm exception handling support'
readme = 'README.md'

# See more keys and definitions at https://docs.wasmer.io/registry/manifest

[dependencies]

[[module]]
name = 'php'
source = 'sapi/cli/php-eh.wasm'
abi = 'wasi'

[[command]]
name = 'php'
module = 'php'

[fs]
"/etc/ssl" = "../php-wasix-deps/openssl/ssl"
"/icu" = "../php-wasix-deps/icu"
