#! /usr/bin/env sh

set -eou

SYSROOT="/Users/syrusakbary/Development/wasix-libc/sysroot"
PHP_WASIX_DEPS="../php-wasix-deps"

export \
  CURL_CFLAGS="-I$PHP_WASIX_DEPS/include/curl" \
  CURL_LIBS="-L$PHP_WASIX_DEPS/lib -lcurl -lcrypto -lssl" \
  ZLIB_CFLAGS="-I$PHP_WASIX_DEPS/include/zlib" \
  ZLIB_LIBS="-L$PHP_WASIX_DEPS/lib -lz" \
  LIBXML_CFLAGS="-I$PHP_WASIX_DEPS/include/libxml2" \
  LIBXML_LIBS="-L$PHP_WASIX_DEPS/lib -lxml2 -llzma" \
  SQLITE_CFLAGS="-I$PHP_WASIX_DEPS/include/sqlite" \
  SQLITE_LIBS="-L$PHP_WASIX_DEPS/lib -lsqlite3" \
  OPENSSL_CFLAGS="-I$PHP_WASIX_DEPS/include/openssl" \
  OPENSSL_LIBS="-L$PHP_WASIX_DEPS/lib -lssl -lcrypto" \
  ICONV_CFLAGS="-I$PHP_WASIX_DEPS/include/iconv" \
  ICONV_LIBS="-L$PHP_WASIX_DEPS/lib -liconv -lcharset -licrt" \
  PHP_BUILD_SYSTEM="clang(WASIX)" \
  PHP_EXTRA_INCLUDES="" \
  PHP_IPV6="yes" \
  RANLIB=llvm-ranlib \
  AR=llvm-ar \
  NM=llvm-nm \
  CC="clang-16 --target=wasm32-wasi --sysroot=$SYSROOT" \
  CXX="clang-16 --target=wasm32-wasi --sysroot=$SYSROOT" \
  CFLAGS="-matomics -mbulk-memory -mmutable-globals -pthread -mthread-model posix -ftls-model=local-exec \
    -fno-trapping-math -D_WASI_EMULATED_MMAN -D_WASI_EMULATED_SIGNAL -D_WASI_EMULATED_PROCESS_CLOCKS \
    -g -flto -O2" \
  LIBS="-Wl,--shared-memory -Wl,--max-memory=4294967296 -Wl,--import-memory -Wl,--export-dynamic \
    -Wl,--export=__heap_base -Wl,--export=__stack_pointer -Wl,--export=__data_end -Wl,--export=__wasm_init_tls \
    -Wl,--export=__wasm_signal -Wl,--export=__tls_size -Wl,--export=__tls_align -Wl,--export=__tls_base \
    -lwasi-emulated-mman -flto -g -Wl,-z,stack-size=8388608 -Wl,--error-limit=0" \

./buildconf --force

./configure --enable-fd-setsize=32768 --enable-static --disable-shared --host=wasm32-wasi --target=wasm32-wasi \
  --enable-opcache --disable-opcache-jit --disable-huge-code-pages --disable-rpath --disable-cgi --with-zlib \
  --with-openssl --enable-mbstring --disable-mbregex --disable-zend-signals --prefix=/usr/bin \
  --with-valgrind=no --with-pcre-jit=no --with-iconv --disable-huge-code-pages --disable-phpdbg \
  --enable-fiber-asm --with-mysqli=mysqlnd --with-pdo-mysql=mysqlnd \
  --with-pgsql=$PHP_WASIX_DEPS/pgsql --with-pdo-pgsql=$PHP_WASIX_DEPS/pgsql \
  --program-suffix=".wasm"

make clean

./wb
