#! /usr/bin/env sh

set -eou

~/repos/wasmer/wasmer/target/release/wasmer run php.wasm \
  --singlepass \
  --env USE_ZEND_ALLOC=0 \
  --net \
  --mapdir /app:../wordpress-wasmer-starter \
  -- \
  -S localhost:8080 \
  -t /app/app \
  -d opcache.enable_cli=1 \
  -d opcache.enable=1
