#! /usr/bin/env sh

set -eou

~/repos/wasmer/wasmer/target/release/wasmer run php.wasm \
  --singlepass \
  --net \
  --mapdir /app:../wordpress-wasmer-starter \
  -- \
  -S localhost:8080 \
  -t /app/app
