name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-test:
    uses: "./.github/workflows/wasix-pr.yaml"
    secrets:
        SENDMAIL_DEFAULT_USERNAME: ${{ secrets.SENDMAIL_DEFAULT_USERNAME }}
        SENDMAIL_DEFAULT_PASSWORD: ${{ secrets.SENDMAIL_DEFAULT_PASSWORD }}

  release:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Setup Wasmer
        uses: wasmerio/setup-wasmer@v3.1

      - name: Check out
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
          path: php

      - name: Check out php-wasix-deps
        uses: actions/checkout@v3
        with:
          repository: wasix-org/php-wasix-deps
          submodules: "recursive"
          path: php-wasix-deps


      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          path: build-artifacts

      - name: Publish
        run: |
          TAG_NAME=${{github.ref_name}}
          VERSION_NUMBER=${TAG_NAME#v}
          echo Publishing version $VERSION_NUMBER

          cd php

          if ! grep -q "version = ['\"]$VERSION_NUMBER['\"]" wasmer.toml; then
            echo Tagged version must match version in wasmer.toml
            exit -1
          fi

          mkdir -p sapi/cli
          mv ../build-artifacts/php-wasix/php.wasm sapi/cli/php.wasm

          wasmer publish --registry="wasmer.io" --token=${{ secrets.WASMER_CIUSER_PROD_TOKEN }} --non-interactive

          echo PHP version $VERSION_NUMBER was published successfully 🎉
